# Generated by Django 3.2.25 on 2026-04-04 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('sn', models.CharField(error_messages={'unique': 'A product with this SN already exists.'}, help_text='Unique stock-keeping unit code. Format examples: CLT-001, ELEC-002, FOOD-003.', max_length=50, unique=True, verbose_name='Product Code (SN)')),
                ('name', models.CharField(help_text='Display name shown in the inventory table and order forms.', max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price per unit (must be ≥ 0).', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Price must be 0 or greater.')], verbose_name='Unit Price')),
                ('stock', models.IntegerField(default=0, help_text='Current on-hand quantity. Updated automatically by inbound/outbound orders.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Stock cannot be negative.')], verbose_name='Stock Quantity')),
                ('description', models.CharField(blank=True, default='', help_text='Short description shown in the product detail tooltip.', max_length=255, verbose_name='Description')),
                ('category', models.ForeignKey(db_column='category_id', help_text='Product category — cannot be deleted while products are assigned.', on_delete=django.db.models.deletion.RESTRICT, to='category.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sn'], name='idx_product_sn'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='idx_product_stock'),
        ),
    ]
