# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('is_deleted', models.BooleanField(default=False, help_text='True means this record is logically deleted and hidden from normal queries.', verbose_name='Soft Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deletion Time')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Lowercase letters, digits, and underscores.', max_length=50, unique=True, verbose_name='Username')),
                ('name', models.CharField(help_text='Real name or display name shown in the UI.', max_length=50, verbose_name='Display Name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('stall_owner', 'Stall Owner'), ('customer', 'Customer')], default='customer', help_text='Determines what the user can access in the system.', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
    ]
