# Generated by Django 3.2.25 on 2026-04-04 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('code', models.CharField(error_messages={'unique': 'An inbound order with this code already exists.'}, help_text='Unique inbound order number. Format from seed data: IN{YYYYMMDD}{sequence}, e.g. IN2024112701.', max_length=50, unique=True, verbose_name='Order Code')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='draft → completed (stock increased) | draft → cancelled.', max_length=10, verbose_name='Status')),
                ('remark', models.CharField(blank=True, default='', help_text='Optional notes about this order.', max_length=255, verbose_name='Remark')),
                ('customer', models.ForeignKey(db_column='customer_id', help_text='The supplier (Customer with type=supplier) for this order.', limit_choices_to={'customer_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='inorder_set', to='customer.customer', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Inbound Order',
                'verbose_name_plural': 'Inbound Orders',
                'db_table': 'inorder',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='InOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Number of units purchased in this line.', validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1.')], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price per unit paid to the supplier.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Unit price cannot be negative.')], verbose_name='Unit Price')),
                ('inorder', models.ForeignKey(db_column='inorder_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inorder.inorder', verbose_name='Inbound Order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inorderproduct_set', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inbound Order Line',
                'verbose_name_plural': 'Inbound Order Lines',
                'db_table': 'inorder_products',
            },
        ),
    ]
