# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='operator',
            field=models.ForeignKey(db_column='user_id', help_text='The user who created/manages this order.', on_delete=django.db.models.deletion.CASCADE, related_name='inorders_operated', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddIndex(
            model_name='inorder',
            index=models.Index(fields=['status'], name='idx_inorder_status'),
        ),
        migrations.AddIndex(
            model_name='inorder',
            index=models.Index(fields=['customer'], name='idx_inorder_customer'),
        ),
        migrations.AddIndex(
            model_name='inorder',
            index=models.Index(fields=['operator'], name='idx_inorder_operator'),
        ),
        migrations.AddIndex(
            model_name='inorder',
            index=models.Index(fields=['create_time'], name='idx_inorder_created'),
        ),
    ]
