# Generated by Django 3.2.25 on 2026-04-04 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('name', models.CharField(help_text='Full name of the supplier or buyer.', max_length=50, verbose_name='Contact Name')),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, optional +, spaces, or hyphens).', regex='^\\+?[\\d\\s\\-]{7,20}$')], verbose_name='Phone Number')),
                ('address', models.CharField(help_text='Business address of the contact.', max_length=128, verbose_name='Address')),
                ('customer_type', models.CharField(choices=[('supplier', 'Supplier'), ('buyer', 'Buyer')], default='buyer', help_text='supplier — provides goods for inbound orders.\nbuyer    — purchases goods via outbound orders.', max_length=10, verbose_name='Contact Type')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['customer_type', 'name'],
            },
        ),
    ]
