# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('name', models.CharField(help_text='Display name of the stall shown in the UI header.', max_length=100, verbose_name='Stall Name')),
                ('description', models.CharField(blank=True, default='', help_text='Short description of the stall and what it sells.', max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='active    — fully operational.\ninactive  — temporarily closed by the stall owner.\nsuspended — suspended by an admin (only admin can unsuspend).', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stall',
                'verbose_name_plural': 'Stalls',
                'db_table': 'stalls',
                'ordering': ['name'],
            },
        ),
    ]
