# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', help_text='The user (role=stall_owner) who operates this stall.', limit_choices_to={'role': 'stall_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to=settings.AUTH_USER_MODEL, verbose_name='Stall Owner'),
        ),
    ]
