# Generated by Django 3.2.25 on 2026-04-04 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('code', models.CharField(error_messages={'unique': 'An outbound order with this code already exists.'}, help_text='Unique outbound order number. Format from seed data: OUT{YYYYMMDD}{sequence}, e.g. OUT2024112701.', max_length=50, unique=True, verbose_name='Order Code')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='draft → completed (stock check + deduction)\ndraft → cancelled (no stock change)\ncompleted → cancelled (stock RESTORED — admin only)', max_length=10, verbose_name='Status')),
                ('remark', models.CharField(blank=True, default='', help_text='Optional notes about this sale.', max_length=255, verbose_name='Remark')),
                ('customer', models.ForeignKey(db_column='customer_id', help_text='The buyer (Customer with type=buyer) for this order.', limit_choices_to={'customer_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='outorder_set', to='customer.customer', verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Outbound Order',
                'verbose_name_plural': 'Outbound Orders',
                'db_table': 'outorder',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OutOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Number of units sold in this line.', validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1.')], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit charged to the buyer.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Unit price cannot be negative.')], verbose_name='Unit Price')),
                ('outorder', models.ForeignKey(db_column='outorder_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outorder.outorder', verbose_name='Outbound Order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='outorderproduct_set', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Outbound Order Line',
                'verbose_name_plural': 'Outbound Order Lines',
                'db_table': 'outorder_products',
            },
        ),
    ]
