# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (set automatically).', verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (updated automatically).', verbose_name='Modification Time')),
                ('content', models.TextField(help_text='The text body of the message.', verbose_name='Message Content')),
                ('is_read', models.BooleanField(default=False, help_text='True when the receiver has read this message.', verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['create_time'],
            },
        ),
    ]
