# Generated by Django 3.2.25 on 2026-04-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(db_column='receiver_id', help_text='The user who should receive this message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver'], name='idx_chat_sender_receiver'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'sender'], name='idx_chat_receiver_sender'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='idx_chat_receiver_read'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['create_time'], name='idx_chat_created'),
        ),
    ]
